[package]
name = "DynaCtrl"
version = "0.1.0"
edition = "2024"

[lib]
name = "dynactrl"
crate-type = ["cdylib"]  # 生成动态链接库

[dependencies]
jni = { version = "0.21.1", default-features = false }
fastrand = "2.3.0"